---
- name: Check if Laravel exist
  ansible.builtin.stat:
    path: "{{ laravel_install_path }}"
  register: app_folder

- block:
  - name: Install laravel with composer
    community.general.composer:
      command: create-project
      arguments: "laravel/laravel {{ laravel_install_path }} {{ laravel_version }}"
      working_dir: /home/{{ laravel_owner }}
      executable: "{{ laravel_php_executable }}"
      composer_executable: "{{ laravel_composer_executable}}"

  become: true
  become_user: "{{ laravel_owner }}"
  when: app_folder.stat.exists == false
